#!/bin/bash
#
# Script to configure cobbler using ansible
#
# Copyright (C) 2016  JingchengYang <yjcyxky@163.com>
#

show_help(){
cat << EOF
usage: $(echo $0) [-h] [-i <command>] [-c <config_file>]
       -h show help document
       -c hpc config file
       -i command name, it can be add_distro, deploy_cobbler, deploy_torque
EOF
}

while getopts ":hc:i:" arg
do
    case "$arg" in
        "i")
            install_command="$OPTARG"
            ;;
        "c")
            config_file="$OPTARG"
            ;;
        "?")
            echo "Unkown option: $OPTARG"
            exit 1
            ;;
        ":")
            echo "No argument value for option $OPTARG"
            ;;
        h)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown error while processing options"
            show_help
            exit 1
            ;;
    esac
done

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

check_arg () {
    if [ -z $1 ];then
        echo "请指定参数$2"
        exit 1
    fi
}

# 检测输入参数
check_arg "$install_command" "-i"
check_arg "$config_file" "-c"

if [ -z `which ansible-playbook` ];then
    echo "请安装ansible"
    exit 1
fi

if [ -z `which python3` ];then
    echo "请安装python3"
    exit 1
fi

# 配置文件是否存在
if [ ! -f "$config_file" ];then
    echo "未找到配置文件: $config_file"
    exit 1
else
    python3 ./init_deploy $config_file
fi

array=("add_distro" "deploy_torque" "deploy_cobbler")

containsElement "$install_command" "${array[@]}"
if [ $? == 0 ]; then
    echo "执行命令：$install_command"
    cd playbook
    ansible-playbook "$install_command".yml
else
    echo "命令${install_command}不存在，请指定add_distro、deploy_torque、deploy_cobbler之一"
    exit 1
fi
